#!/bin/bash

# transfer - Copy contents and preserve timestamps
# Copyright (c) 2025 Rogerio O. Ferraz <rogerio.o.ferraz@gmail.com>

# MIT License

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -euo pipefail

SCRIPTNAME="$(basename -- ${0})"

USAGE="
transfer - Copy contents and preserve timestamps

Copy content from source files to destination files, preserving the timestamps of destination files.

Usage: ${SCRIPTNAME} [OPTIONS] source_pattern dest_pattern

ARGUMENTS:
  source_pattern : source file(s) naming pattern
  dest_pattern   : destination file(s) naming pattern

OPTIONS:
  -D, --debug    : Enable debug output
  -h, --help     : Display usage information
  -V, --version  : Show current version

Example:

  $ ${SCRIPTNAME} fixed_Screenshot*.png Screenshot*.png

  Move contents of fixed_Screenshot*.png files to Screenshot*.png files,
  while keeping the timestamps of Screenshot*.png files unchanged
"

VERSION="
${SCRIPTNAME} 1.0.1
Copyright (c) 2025 Rogerio O. Ferraz <rogerio.o.ferraz@gmail.com>
MIT License <https://github.com/rogeriooferraz/transfer/blob/main/LICENSE>
This is free and open source software.
There is NO WARRANTY, to the extent permitted by law.
"

# Options
while [ "${#}" -gt 0 ] ; do
  case "${1:-}" in
    --debug|-D)
      shift
      set -x
      ;;
    --help|-h)
      echo "${USAGE}"
      exit 0
      ;;
    --version|-V)
      echo "${VERSION}"
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

# Validate user input
if [ "$#" -ne 2 ]; then
  echo "error: invalid number of arguments" >&2
  echo "See '${SCRIPTNAME} --help' for more information" >&2
  exit 1
fi

SRC_PATTERN="${1}"
DST_PATTERN="${2}"

readarray -t SRC_FILES < <(compgen -G "${SRC_PATTERN}" | sort)
readarray -t DST_FILES < <(compgen -G "${DST_PATTERN}" | sort)

if [ "${#SRC_FILES[@]}" -eq 0 ] ; then
  echo "error: invalid source files" >&2
  exit 2
fi

if [ "${#DST_FILES[@]}" -eq 0 ] ; then
  echo "error: invalid destination files" >&2
  exit 3
fi

if [ "${#SRC_FILES[@]}" -ne "${#DST_FILES[@]}" ]; then
  echo "error: number of source and destination files does not match: "${#SRC_FILES[@]}" vs "${#DST_FILES[@]}"" >&2
  exit 4
fi

for i in "${!SRC_FILES[@]}"; do
  SRC_FILE="${SRC_FILES[$i]}"
  DST_FILE="${DST_FILES[$i]}"

  if [ ! -f "${SRC_FILE}" ]; then
    echo "error: source file not found: ${SRC_FILE}" >&2
    exit 5
  fi
  if [ ! -f "${DST_FILE}" ]; then
    echo "error: destination file not found: ${DST_FILE}" >&2
    exit 6
  fi

  touch -r "${DST_FILE}" "${SRC_FILE}"
  mv -- "${SRC_FILE}" "${DST_FILE}"
done

exit 0
